const localImages = {
  pizza: require('../../assets/pizza.png'),
  hamburger: require('../../assets/hamburger.png'),
  steakhouse: require('../../assets/steakhouse.png'),
  sandwich: require('../../assets/sandwich.png'),
  coffee: require('../../assets/coffee.png'),
  icecream: require('../../assets/icecream.png'),
  turkish: require('../../assets/turkish.gif'),
  usa: require('../../assets/usa.gif'),
  england: require('../../assets/england.gif'),
  greece: require('../../assets/greece.gif'),
  france: require('../../assets/france.gif'),
  italy: require('../../assets/italy.gif'),
  china: require('../../assets/china.gif'),
  japan: require('../../assets/japan.gif'),
  india: require('../../assets/india.gif'),
  indonesia: require('../../assets/indonesia.gif'),
  lebanon: require('../../assets/lebanon.gif'),
  mexico: require('../../assets/mexico.gif'),
  spain: require('../../assets/spain.gif'),
  thailand: require('../../assets/thailand.gif'),
  vietnam: require('../../assets/vietnam.gif'),
  bakery: require('../../assets/bakery.png'),
  barbecue: require('../../assets/barbecue.png'),
  brazil: require('../../assets/brazil.gif'),
  korea: require('../../assets/korea.gif'),
  seafood: require('../../assets/seafood.png'),
  fastfood: require('../../assets/fastfood.png'),
  cafe: require('../../assets/cafe.png'),
  bar: require('../../assets/bar.png'),
  breakfast: require('../../assets/breakfast.png'),
  mediterranean: require('../../assets/mediterranean.png'),
  takeaway: require('../../assets/takeaway.png'),
  delivery: require('../../assets/delivery.png'),
  brunch: require('../../assets/brunch.png'),
  vegan: require('../../assets/vegan.png'),
  vegetarian: require('../../assets/vegetarian.png'),
  sushi: require('../../assets/sushi.png'),
  ramen: require('../../assets/ramen.png'),
  middle: require('../../assets/middle.png'),
};

export default localImages;
